/**
 * Full-pass enrichment for all AnimalUse records:
 * better sources, relationship fixes, and local/remote images.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const usesPath = path.join(root, "src", "data", "uses.json");
const outDir = path.join(root, "public", "mascots");
fs.mkdirSync(outDir, { recursive: true });

const uses = JSON.parse(fs.readFileSync(usesPath, "utf8"));

/** @type {Record<string, Partial<{
  sourceUrl: string;
  sourceType: 'official'|'community_primary'|'secondary';
  relationshipType: string;
  officialStatus: 'official'|'unofficial'|'unknown';
  activeStatus: 'active'|'inactive';
  recognition: string;
  verificationStatus: string;
  product: string;
  characterName: string;
  file: string;
  imageUrl: string;
  attribution: string;
  alt: string;
  techHabitats: string[];
}>>} */
const enrich = {
  "penguin-linux-tux": {
    sourceUrl: "https://www.kernel.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "linux-tux.png",
    imageUrl: "https://www.kernel.org/theme/images/logos/tux.png",
    attribution: "Official Tux artwork from kernel.org.",
    alt: "Tux, the Linux penguin mascot",
  },
  "penguin-tencent-qq": {
    sourceUrl: "https://im.qq.com/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "tencent-qq.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/tencentqq.svg",
    attribution: "Tencent QQ brand mark via Simple Icons.",
    alt: "Tencent QQ brand mark",
  },
  "elephant-postgresql-slonik": {
    sourceUrl: "https://www.postgresql.org/about/policies/trademarks/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "postgresql-elephant.png",
    imageUrl: "https://www.postgresql.org/media/img/about/press/elephant.png",
    attribution: "Official PostgreSQL elephant logo.",
    alt: "PostgreSQL elephant logo (Slonik)",
  },
  "elephant-php-elephpant": {
    sourceUrl: "https://www.php.net/elephpant.php",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "php-logo.svg",
    imageUrl: "https://www.php.net/images/logos/php-logo.svg",
    attribution: "Official PHP logo from php.net.",
    alt: "PHP logo representing elePHPant",
  },
  "elephant-apache-hadoop": {
    sourceUrl: "https://hadoop.apache.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "apache-hadoop.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apachehadoop.svg",
    attribution: "Apache Hadoop brand mark via Simple Icons.",
    alt: "Apache Hadoop brand mark",
  },
  "elephant-evernote": {
    sourceUrl: "https://evernote.com/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "evernote.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/evernote.svg",
    attribution: "Evernote brand mark via Simple Icons.",
    alt: "Evernote elephant brand mark",
  },
  "elephant-salesforce-ruth": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Ruth",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "owl-duolingo-duo": {
    sourceUrl: "https://blog.duolingo.com/how-we-reinvented-the-duo-owl/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "duolingo.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/duolingo.svg",
    attribution: "Duolingo brand mark via Simple Icons.",
    alt: "Duolingo brand mark for Duo the owl",
  },
  "owl-hootsuite-owly": {
    sourceUrl: "https://www.hootsuite.com/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "hootsuite.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/hootsuite.svg",
    attribution: "Hootsuite brand mark via Simple Icons.",
    alt: "Hootsuite brand mark for Owly",
  },
  "owl-tripadvisor": {
    sourceUrl: "https://www.tripadvisor.com/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "tripadvisor.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/tripadvisor.svg",
    attribution: "Tripadvisor brand mark via Simple Icons.",
    alt: "Tripadvisor owl brand mark",
  },
  "owl-salesforce-hootie": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Hootie",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "whale-docker-moby-dock": {
    sourceUrl: "https://www.docker.com/blog/call-me-moby-dock/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "docker-moby.png",
    imageUrl: "https://www.docker.com/wp-content/uploads/2022/03/Moby-logo.png",
    attribution: "Official Moby Dock mark from Docker.",
    alt: "Moby Dock, the Docker whale mascot",
  },
  "whale-moby-project": {
    sourceUrl: "https://mobyproject.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "Moby Project",
    techHabitats: ["code", "open_source"],
  },
  "fox-mozilla-firefox": {
    sourceUrl: "https://www.mozilla.org/firefox/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "firefox.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/firefoxbrowser.svg",
    attribution: "Firefox brand mark via Simple Icons.",
    alt: "Mozilla Firefox brand mark",
  },
  "fox-gitlab-ish": {
    sourceUrl: "https://about.gitlab.com/blog/gitlab-is-a-tanuki-not-a-fox/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "GitLab",
    // GitLab clarified tanuki, not fox — keep as soft association
    recognition: "niche",
    file: "gitlab.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gitlab.svg",
    attribution: "GitLab brand mark via Simple Icons.",
    alt: "GitLab brand mark",
  },
  "fox-salesforce-brandy": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Brandy",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "cat-scratch-cat": {
    sourceUrl: "https://scratch.mit.edu/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "scratch.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/scratch.svg",
    attribution: "Scratch brand mark via Simple Icons.",
    alt: "Scratch Cat brand mark",
  },
  "cat-github-octocat": {
    sourceUrl: "https://octodex.github.com/",
    sourceType: "official",
    relationshipType: "hybrid_or_mythical",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "github-octocat.png",
    imageUrl: "https://octodex.github.com/images/original.png",
    attribution: "Official Octocat from Octodex.",
    alt: "GitHub Octocat",
  },
  // Removed: Yarn→cat was an invented stretch (no animal in the brand).
  "crab-rust-ferris": {
    sourceUrl: "https://rustacean.net/",
    sourceType: "community_primary",
    relationshipType: "community_mascot",
    officialStatus: "unofficial",
    verificationStatus: "verified",
    file: "rust-ferris.svg",
    imageUrl: "https://rustacean.net/assets/cuddlyferris.svg",
    attribution: "Ferris the crab from rustacean.net (community mascot).",
    alt: "Ferris, the Rust community crab mascot",
  },
  "gopher-go-the-go-gopher": {
    sourceUrl: "https://go.dev/blog/gopher",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "go-gopher.png",
    imageUrl: "https://go.dev/blog/gopher/gopher.png",
    attribution: "Official Go gopher artwork.",
    alt: "The Go Gopher",
  },
  "dolphin-mysql-sakila": {
    sourceUrl: "https://dev.mysql.com/doc/refman/9.3/en/history.html",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "mysql-logo.svg",
    imageUrl: "https://labs.mysql.com/common/logos/mysql-logo.svg?v2",
    attribution: "Official MySQL logo.",
    alt: "MySQL logo for Sakila the dolphin",
  },
  "monkey-mailchimp-freddie": {
    sourceUrl: "https://mailchimp.com/about/brand-assets/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "mailchimp.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/mailchimp.svg",
    attribution: "Mailchimp brand mark via Simple Icons.",
    alt: "Mailchimp brand mark for Freddie",
  },
  "monkey-surveymonkey": {
    sourceUrl: "https://www.surveymonkey.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "surveymonkey.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/surveymonkey.svg",
    attribution: "SurveyMonkey brand mark via Simple Icons.",
    alt: "SurveyMonkey brand mark",
  },
  "monkey-blender-suzanne": {
    sourceUrl: "https://docs.blender.org/manual/en/latest/glossary/index.html#term-Suzanne",
    sourceType: "official",
    relationshipType: "community_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Suzanne",
    product: "Blender",
    techHabitats: ["tools"],
    file: "blender.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/blender.svg",
    attribution: "Blender brand mark via Simple Icons.",
    alt: "Blender brand mark for Suzanne",
  },
  "duck-duckduckgo": {
    sourceUrl: "https://duckduckgo.com/about",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "duckduckgo.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/duckduckgo.svg",
    attribution: "DuckDuckGo brand mark via Simple Icons.",
    alt: "DuckDuckGo brand mark",
  },
  "duck-adium-adiumy": {
    sourceUrl: "https://adium.im/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    activeStatus: "inactive",
    verificationStatus: "partially_verified",
    characterName: "Adiumy",
    product: "Adium",
    techHabitats: ["apps", "web"],
  },
  "chameleon-suse-geeko": {
    sourceUrl: "https://www.suse.com/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "suse.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/suse.svg",
    attribution: "SUSE brand mark via Simple Icons.",
    alt: "SUSE brand mark for Geeko",
  },
  "hedgehog-posthog": {
    sourceUrl: "https://posthog.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "posthog.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/posthog.svg",
    attribution: "PostHog brand mark via Simple Icons.",
    alt: "PostHog brand mark",
  },
  "dinosaur-deno": {
    sourceUrl: "https://deno.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "deno-logo.svg",
    imageUrl: "https://deno.land/logo.svg",
    attribution: "Official Deno logo.",
    alt: "Deno logo",
  },
  "dinosaur-mozilla-historical": {
    sourceUrl: "https://wiki.mozilla.org/Logos",
    sourceType: "secondary",
    relationshipType: "historical",
    officialStatus: "official",
    activeStatus: "inactive",
    verificationStatus: "historical_verified",
    product: "Mozilla",
    recognition: "niche",
  },
  "beaver-dbeaver": {
    sourceUrl: "https://dbeaver.io/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "dbeaver.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/dbeaver.svg",
    attribution: "DBeaver brand mark via Simple Icons.",
    alt: "DBeaver brand mark",
  },
  "cockroach-cockroachdb": {
    sourceUrl: "https://www.cockroachlabs.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "cockroachdb.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/cockroachlabs.svg",
    attribution: "CockroachDB brand mark via Simple Icons.",
    alt: "CockroachDB brand mark",
  },
  "red-panda-redpanda": {
    sourceUrl: "https://www.redpanda.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    // No redistributable Redpanda mark packaged yet.
  },
  "red-panda-kotlin-kodi": {
    sourceUrl: "https://kotlinlang.org/docs/kotlin-mascot.html",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Kodee",
    product: "Kotlin",
    techHabitats: ["code", "open_source"],
    file: "kotlin-kodee.svg",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Kodee-mascot-regular.svg",
    attribution: "Kotlin Kodee mascot via Wikimedia Commons.",
    alt: "Kotlin Kodee mascot",
  },
  "lion-brave-browser": {
    sourceUrl: "https://brave.com/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "brave.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/brave.svg",
    attribution: "Brave brand mark via Simple Icons.",
    alt: "Brave Browser brand mark",
  },
  "lion-liongard": {
    sourceUrl: "https://www.liongard.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    product: "Liongard",
    techHabitats: ["tools"],
  },
  "otter-otter-ai": {
    sourceUrl: "https://otter.ai/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "otter-ai.ico",
    imageUrl: "https://otter.ai/favicon.ico",
    attribution: "Otter.ai favicon from otter.ai.",
    alt: "Otter.ai brand mark",
  },
  "camel-perl": {
    sourceUrl: "https://www.perl.org/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "perl.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/perl.svg",
    attribution: "Perl brand mark via Simple Icons.",
    alt: "Perl camel brand mark",
  },
  "puffin-prestashop-preston": {
    sourceUrl: "https://www.prestashop-project.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "prestashop.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/prestashop.svg",
    attribution: "PrestaShop brand mark via Simple Icons.",
    alt: "PrestaShop brand mark for Preston",
  },
  "pufferfish-openbsd-puffy": {
    sourceUrl: "https://www.openbsd.org/art.html",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Puffy",
    product: "OpenBSD",
    techHabitats: ["code", "open_source"],
    file: "openbsd.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/openbsd.svg",
    attribution: "OpenBSD brand mark via Simple Icons.",
    alt: "OpenBSD brand mark for Puffy",
  },
  "rabbit-plan-9-glenda": {
    sourceUrl: "https://9p.io/plan9/glenda.html",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Glenda",
    product: "Plan 9",
    techHabitats: ["code", "open_source"],
  },
  // Removed: Bun→rabbit was an invented stretch (no animal in the brand).
  "squirrel-apache-flink": {
    sourceUrl: "https://flink.apache.org/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    product: "Apache Flink",
    techHabitats: ["data"],
    file: "apacheflink.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apacheflink.svg",
    attribution: "Apache Flink brand mark via Simple Icons.",
    alt: "Apache Flink squirrel brand mark",
  },
  "squirrel-krita-kiki": {
    sourceUrl: "https://krita.org/en/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Kiki",
    product: "Krita",
    techHabitats: ["tools"],
    file: "krita.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/krita.svg",
    attribution: "Krita brand mark via Simple Icons.",
    alt: "Krita brand mark for Kiki",
  },
  "squirrel-salesforce-flo": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Flo",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "mule-emule": {
    sourceUrl: "https://www.emule-project.net/",
    sourceType: "official",
    relationshipType: "historical",
    officialStatus: "official",
    activeStatus: "inactive",
    verificationStatus: "historical_verified",
    product: "eMule",
    techHabitats: ["apps", "web"],
  },
  "pigeon-pidgin-purple-pidgin": {
    sourceUrl: "https://pidgin.im/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Purple Pidgin",
    product: "Pidgin",
    techHabitats: ["apps", "web"],
    file: "pidgin.svg",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Pidgin.svg",
    attribution: "Pidgin brand mark via Simple Icons.",
    alt: "Pidgin brand mark",
  },
  "parrot-parrot-os": {
    sourceUrl: "https://parrotsec.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "parrot-os.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/parrotsecurity.svg",
    attribution: "Parrot OS brand mark via Simple Icons.",
    alt: "Parrot OS brand mark",
  },
  "panda-pandadoc": {
    sourceUrl: "https://www.pandadoc.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "pandadoc.png",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/PandaDoc%20Logo%20PNG.png",
    attribution: "PandaDoc brand mark via Simple Icons.",
    alt: "PandaDoc brand mark",
  },
  "raccoon-salesforce-astro": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Astro",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
    file: "salesforce.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/salesforce.svg",
    attribution: "Salesforce brand mark via Simple Icons.",
    alt: "Salesforce brand mark for Astro",
  },
  "shark-digitalocean-sammy": {
    sourceUrl: "https://www.digitalocean.com/blog/meet-sammy-digitaloceans-friendly-mascot",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "digitalocean.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/digitalocean.svg",
    attribution: "DigitalOcean brand mark via Simple Icons.",
    alt: "DigitalOcean brand mark for Sammy",
  },
  "dog-datadog-bits": {
    sourceUrl: "https://www.datadoghq.com/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "datadog.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/datadog.svg",
    attribution: "Datadog brand mark via Simple Icons.",
    alt: "Datadog brand mark for Bits",
  },
  "seal-mariadb": {
    sourceUrl: "https://mariadb.org/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "mariadb.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/mariadb.svg",
    attribution: "MariaDB brand mark via Simple Icons.",
    alt: "MariaDB brand mark",
  },
  "snake-python": {
    sourceUrl: "https://www.python.org/community/logos/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "python.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/python.svg",
    attribution: "Python brand mark via Simple Icons.",
    alt: "Python snakes logo",
  },
  "hummingbird-dart-flutter-dash": {
    sourceUrl: "https://docs.flutter.dev/dash",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "flutter-dash.png",
    imageUrl: "https://docs.flutter.dev/assets/images/dash/Dash.png",
    attribution: "Official Dash mascot from Flutter docs.",
    alt: "Dash, the Flutter hummingbird mascot",
  },
  "mastodon-mastodon": {
    sourceUrl: "https://joinmastodon.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "mastodon.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/mastodon.svg",
    attribution: "Mastodon brand mark via Simple Icons.",
    alt: "Mastodon brand mark",
  },
  "zebra-zebra-technologies": {
    sourceUrl: "https://www.zebra.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "Zebra Technologies",
    techHabitats: ["tools"],
  },
  "zebra-salesforce-zig": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Zig",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "bee-apache-hive": {
    sourceUrl: "https://hive.apache.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "Apache Hive",
    techHabitats: ["data"],
    file: "apache.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apache.svg",
    attribution: "Apache brand mark via Simple Icons.",
    alt: "Apache brand mark for Hive",
  },
  "pig-apache-pig": {
    sourceUrl: "https://pig.apache.org/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "Apache Pig",
    techHabitats: ["data"],
    file: "apache.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apache.svg",
    attribution: "Apache brand mark via Simple Icons.",
    alt: "Apache brand mark for Pig",
  },
  "octopus-github-mona-the-octocat": {
    sourceUrl: "https://octodex.github.com/",
    sourceType: "official",
    relationshipType: "hybrid_or_mythical",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "github-octocat.png",
    imageUrl: "https://octodex.github.com/images/original.png",
    attribution: "Official Octocat from Octodex.",
    alt: "Mona the Octocat",
  },
  "wombat-npm-wombat": {
    sourceUrl: "https://github.com/npm/cli",
    sourceType: "community_primary",
    relationshipType: "community_mascot",
    officialStatus: "unofficial",
    verificationStatus: "partially_verified",
    file: "npm.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/npm.svg",
    attribution: "npm brand mark via Simple Icons.",
    alt: "npm brand mark for Wombat",
  },
  "gnu-gnu-project": {
    sourceUrl: "https://www.gnu.org/graphics/agnuhead.html",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "gnu.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gnu.svg",
    attribution: "GNU brand mark via Simple Icons.",
    alt: "GNU Project wildebeest mark",
  },
  "weasel-v-veasel": {
    sourceUrl: "https://blog.vlang.io/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "vlang.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/v.svg",
    attribution: "V language brand mark via Simple Icons.",
    alt: "V language brand mark for Veasel",
  },
  "antelope-libreboot-canteloupe": {
    sourceUrl: "https://libreboot.org/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "libreboot.svg",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Libreboot_logo.svg",
    attribution: "Libreboot brand mark via Simple Icons.",
    alt: "Libreboot brand mark",
  },
  "butterfly-raku-camelia": {
    sourceUrl: "https://raku.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "raku-camelia.svg",
    imageUrl: "https://commons.wikimedia.org/wiki/Special:FilePath/Camelia.svg",
    attribution: "Raku brand mark via Simple Icons.",
    alt: "Raku brand mark for Camelia",
  },
  "firefly-apache-beam-firefly": {
    sourceUrl: "https://beam.apache.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "apache.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/apache.svg",
    attribution: "Apache brand mark via Simple Icons.",
    alt: "Apache Beam Firefly brand mark",
  },
  "ladybug-serenityos-buggie": {
    sourceUrl: "https://serenityos.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Buggie",
    product: "SerenityOS",
    techHabitats: ["code", "open_source"],
  },
  "ladybug-bugzilla-buggie": {
    sourceUrl: "https://www.bugzilla.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Buggie",
    product: "Bugzilla",
    techHabitats: ["tools"],
  },
  "fish-freedos-blinky": {
    sourceUrl: "https://www.freedos.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Blinky",
    product: "FreeDOS",
    techHabitats: ["code", "open_source"],
    file: "freedos.svg",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/FreeDOS%20logo4%202010.svg",
    attribution: "FreeDOS brand mark via Simple Icons.",
    alt: "FreeDOS brand mark for Blinky",
  },
  "platypus-darwin-hexley": {
    sourceUrl: "https://www.hexley.com/",
    sourceType: "community_primary",
    relationshipType: "official_mascot",
    officialStatus: "unofficial",
    verificationStatus: "partially_verified",
    characterName: "Hexley",
    product: "Darwin",
    techHabitats: ["code", "open_source"],
  },
  "pony-pony-programming-language": {
    sourceUrl: "https://www.ponylang.io/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "Pony",
    techHabitats: ["code", "open_source"],
  },
  "dragon-kde-konqi": {
    sourceUrl: "https://community.kde.org/Promo/Material/Mascots",
    sourceType: "official",
    relationshipType: "hybrid_or_mythical",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "kde.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/kde.svg",
    attribution: "KDE brand mark via Simple Icons.",
    alt: "KDE brand mark for Konqi",
  },
  "woodpecker-kate-cyber-woodpecker": {
    sourceUrl: "https://kate-editor.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Cyber Woodpecker",
    product: "Kate",
    techHabitats: ["tools"],
    file: "kate.svg",
    imageUrl:
      "https://commons.wikimedia.org/wiki/Special:FilePath/Sc-apps-kate-editor.svg",
    attribution: "Kate brand mark via Simple Icons.",
    alt: "Kate editor brand mark",
  },
  "cow-gentoo-larry-the-cow": {
    sourceUrl: "https://www.gentoo.org/",
    sourceType: "community_primary",
    relationshipType: "community_mascot",
    officialStatus: "unofficial",
    verificationStatus: "partially_verified",
    characterName: "Larry the Cow",
    product: "Gentoo",
    techHabitats: ["code", "open_source"],
    file: "gentoo.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gentoo.svg",
    attribution: "Gentoo brand mark via Simple Icons.",
    alt: "Gentoo brand mark for Larry the Cow",
  },
  "cow-terminusdb-cowduck": {
    sourceUrl: "https://terminusdb.com/",
    sourceType: "official",
    relationshipType: "hybrid_or_mythical",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "CowDuck",
    product: "TerminusDB",
    techHabitats: ["data"],
  },
  "mouse-xfce-mouse": {
    sourceUrl: "https://xfce.org/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    file: "xfce.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/xfce.svg",
    attribution: "Xfce brand mark via Simple Icons.",
    alt: "Xfce mouse brand mark",
  },
  "bear-salesforce-codey": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Codey",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "goat-salesforce-cloudy": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Cloudy",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "horse-salesforce-blaze": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Blaze",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
  },
  "tanuki-salesforce-astro": {
    sourceUrl: "https://www.salesforce.com/blog/meet-trailhead-characters-blog/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Astro",
    product: "Trailhead",
    techHabitats: ["apps", "web"],
    file: "salesforce.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/salesforce.svg",
    attribution: "Salesforce brand mark via Simple Icons.",
    alt: "Salesforce brand mark for Astro the tanuki",
  },
  "tanuki-gitlab-origin-story": {
    sourceUrl: "https://about.gitlab.com/blog/gitlab-is-a-tanuki-not-a-fox/",
    sourceType: "official",
    relationshipType: "animal_logo",
    officialStatus: "official",
    verificationStatus: "verified",
    product: "GitLab",
    techHabitats: ["code", "open_source"],
    file: "gitlab.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/gitlab.svg",
    attribution: "GitLab brand mark via Simple Icons.",
    alt: "GitLab tanuki brand mark",
  },
  "thunderbird-mozilla-thunderbird": {
    sourceUrl: "https://blog.thunderbird.net/2023/05/introducing-the-brand-new-thunderbird-logo/",
    sourceType: "official",
    relationshipType: "hybrid_or_mythical",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "thunderbird.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/thunderbird.svg",
    attribution: "Thunderbird brand mark via Simple Icons.",
    alt: "Mozilla Thunderbird brand mark",
  },
  "cuttlefish-peertube-sepia": {
    sourceUrl: "https://joinpeertube.org/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    characterName: "Sepia",
    product: "PeerTube",
    techHabitats: ["apps", "web"],
    file: "peertube.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/peertube.svg",
    attribution: "PeerTube brand mark via Simple Icons.",
    alt: "PeerTube brand mark for Sepia",
  },
  "iguana-zig-ziguanas": {
    sourceUrl: "https://ziglang.org/",
    sourceType: "community_primary",
    relationshipType: "community_mascot",
    officialStatus: "unofficial",
    verificationStatus: "partially_verified",
    characterName: "Ziguanas",
    product: "Zig",
    techHabitats: ["code", "open_source"],
    file: "zig.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/zig.svg",
    attribution: "Zig brand mark via Simple Icons.",
    alt: "Zig brand mark",
  },
  "llama-meta-llama": {
    sourceUrl: "https://www.llama.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "meta.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/meta.svg",
    attribution: "Meta brand mark via Simple Icons.",
    alt: "Meta Llama brand mark",
  },
  "giraffe-cncf-phippy": {
    sourceUrl: "https://www.cncf.io/phippy/",
    sourceType: "official",
    relationshipType: "official_mascot",
    officialStatus: "official",
    verificationStatus: "verified",
    characterName: "Phippy",
    product: "CNCF",
    techHabitats: ["code", "open_source"],
    file: "cncf.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/cncf.svg",
    attribution: "CNCF brand mark via Simple Icons.",
    alt: "CNCF brand mark for Phippy",
  },
  "donkey-edonkey-historical": {
    sourceUrl: "https://en.wikipedia.org/wiki/EDonkey2000",
    sourceType: "secondary",
    relationshipType: "historical",
    officialStatus: "official",
    activeStatus: "inactive",
    verificationStatus: "historical_verified",
    product: "eDonkey2000",
    techHabitats: ["apps", "web"],
    recognition: "niche",
  },
  "gorilla-gorilla-logic": {
    sourceUrl: "https://gorillalogic.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "partially_verified",
    product: "Gorilla Logic",
    techHabitats: ["tools"],
  },
  "rhino-rhinoceros-3d": {
    sourceUrl: "https://www.rhino3d.com/",
    sourceType: "official",
    relationshipType: "animal_name",
    officialStatus: "official",
    verificationStatus: "verified",
    file: "rhinoceros.svg",
    imageUrl: "https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/rhinoceros.svg",
    attribution: "Rhinoceros 3D brand mark via Simple Icons.",
    alt: "Rhinoceros 3D brand mark",
  },
  "tiger-macos-tiger-historical": {
    sourceUrl: "https://en.wikipedia.org/wiki/Mac_OS_X_Tiger",
    sourceType: "secondary",
    relationshipType: "historical",
    officialStatus: "official",
    activeStatus: "inactive",
    verificationStatus: "historical_verified",
    product: "Mac OS X Tiger",
    techHabitats: ["tools"],
    recognition: "strong_niche",
  },
};

async function download(url, dest) {
  if (fs.existsSync(dest)) return true;
  try {
    const res = await fetch(url, {
      headers: { "User-Agent": "SiliconZooAssetBot/1.0" },
      redirect: "follow",
    });
    if (!res.ok) {
      console.warn(`FAIL ${res.status} ${url}`);
      return false;
    }
    fs.writeFileSync(dest, Buffer.from(await res.arrayBuffer()));
    console.log(`OK   ${path.basename(dest)}`);
    return true;
  } catch (error) {
    console.warn(`ERR  ${url} :: ${error.message}`);
    return false;
  }
}

const notice = [
  "# Third-party assets",
  "",
  "These files are used for identification and commentary. They remain owned by their respective trademark holders and are **not** covered by the MIT or CC BY licenses of this repository.",
  "",
  "| File | Used by | Source | Notes |",
  "| --- | --- | --- | --- |",
];

let updated = 0;
let downloaded = 0;
let stillPending = 0;

for (const use of uses) {
  const patch = enrich[use.id];
  if (!patch) {
    console.warn(`No enrichment for ${use.id}`);
    stillPending++;
    continue;
  }

  if (patch.sourceUrl) use.sourceUrl = patch.sourceUrl;
  if (patch.sourceType) use.sourceType = patch.sourceType;
  if (patch.relationshipType) use.relationshipType = patch.relationshipType;
  if (patch.officialStatus) use.officialStatus = patch.officialStatus;
  if (patch.activeStatus) use.activeStatus = patch.activeStatus;
  if (patch.recognition) use.recognition = patch.recognition;
  if (patch.verificationStatus) use.verificationStatus = patch.verificationStatus;
  if (patch.product) use.product = patch.product;
  if (patch.characterName) use.characterName = patch.characterName;
  if (patch.techHabitats) use.techHabitats = patch.techHabitats;
  use.verifiedAt = "2026-07-21";

  const alt =
    patch.alt ||
    use.image?.alt ||
    `${use.characterName || use.organization} ${use.animalId}`;

  if (patch.file && patch.imageUrl) {
    const dest = path.join(outDir, patch.file);
    const ok = await download(patch.imageUrl, dest);
    if (ok) {
      downloaded++;
      use.image = {
        src: `/mascots/${patch.file}`,
        remoteSrc: patch.imageUrl,
        alt,
        attribution: patch.attribution || "Brand asset",
      };
      notice.push(
        `| \`${patch.file}\` | \`${use.id}\` | ${patch.imageUrl} | ${patch.attribution || "Brand asset"} |`,
      );
    } else {
      use.image = {
        src: null,
        remoteSrc: patch.imageUrl,
        alt,
        attribution: patch.attribution || "Brand asset",
      };
    }
  } else if (!use.image?.src) {
    use.image = use.image || null;
  }

  if (use.sourceUrl.includes("example.com")) stillPending++;
  updated++;
}

fs.writeFileSync(usesPath, JSON.stringify(uses, null, 2) + "\n");
fs.writeFileSync(path.join(root, "THIRD_PARTY_ASSETS.md"), notice.join("\n") + "\n");

const withLocal = uses.filter((u) => u.image?.src).length;
const withSource = uses.filter((u) => !u.sourceUrl.includes("example.com")).length;
const verified = uses.filter((u) =>
  ["verified", "historical_verified"].includes(u.verificationStatus),
).length;

console.log(
  JSON.stringify(
    {
      updated,
      downloadedAttempts: downloaded,
      withLocal,
      withRealSource: withSource,
      verifiedOrHistorical: verified,
      stillExampleSources: uses.filter((u) => u.sourceUrl.includes("example.com")).length,
    },
    null,
    2,
  ),
);
